import {
  blackA,
  blueDark,
  crimson,
  cyanDark,
  grass,
  green,
  indigo,
  indigoDark,
  mauve,
  mint,
  pink,
  plum,
  purple,
  red,
  sage,
  skyDark,
  slateDark,
  teal,
  tomato,
  violet,
  whiteA,
} from '@radix-ui/colors';
import { createStitches } from '@stitches/react';
import type * as Stitches from '@stitches/react';

export const { styled, config, theme, createTheme, globalCss } =
  createStitches({
    theme: {
      colors: {
        ...teal,
        ...mint,
        ...green,
        ...sage,
        ...grass,
        ...whiteA,
        ...blackA,

        // App backgrounds and raised components
        // 1 - 2 - 3
        // normal, hover, active. Buttons are +1 to each
        // 3 - 4 - 5
        // borders non-interactive, interactive, hover
        // 6 - 7 - 8
        // pure color & solid bg
        // 9 - 10
        // low and high contrast text
        // 11 - 12
        // Dark modes use the same scale

        base1: '$sage1',
        base2: '$sage2',
        base3: '$sage3',
        base4: '$sage4',
        base5: '$sage5',
        base6: '$sage6',
        base7: '$sage7',
        base8: '$sage8',
        base9: '$sage9',
        base10: '$sage10',
        base11: '$sage11',
        base12: '$sage12',

        accent1: '$mint1',
        accent2: '$mint2',
        accent3: '$mint3',
        accent4: '$mint4',
        accent5: '$mint5',
        accent6: '$mint6',
        accent7: '$mint7',
        accent8: '$mint8',
        accent9: '$mint9',
        accent10: '$mint10',
        accent11: '$mint11',
        accent12: '$mint12',

        secondary1: '$teal1',
        secondary2: '$teal2',
        secondary3: '$teal3',
        secondary4: '$teal4',
        secondary5: '$teal5',
        secondary6: '$teal6',
        secondary7: '$teal7',
        secondary8: '$teal8',
        secondary9: '$teal9',
        secondary10: '$teal10',
        secondary11: '$teal11',
        secondary12: '$teal12',

        primary1: '$green1',
        primary2: '$green2',
        primary3: '$green3',
        primary4: '$green4',
        primary5: '$green5',
        primary6: '$green6',
        primary7: '$green7',
        primary8: '$green8',
        primary9: '$green9',
        primary10: '$green10',
        primary11: '$green11',
        primary12: '$green12',

        shade1: '$grass1',
        shade2: '$grass2',
        shade3: '$grass3',
        shade4: '$grass4',
        shade5: '$grass5',
        shade6: '$grass6',
        shade7: '$grass7',
        shade8: '$grass8',
        shade9: '$grass9',
        shade10: '$grass10',
        shade11: '$grass11',
        shade12: '$grass12',

        tint1: '$teal1',
        tint2: '$teal2',
        tint3: '$teal3',
        tint4: '$teal4',
        tint5: '$teal5',
        tint6: '$teal6',
        tint7: '$teal7',
        tint8: '$teal8',
        tint9: '$teal9',
        tint10: '$teal10',
        tint11: '$teal11',
        tint12: '$teal12',

        appBg1: '$base1',
        appBg2: '$base2',
        appBg3: '$base9',
        appBg4: '$base10',
        lowContrast: '$base11',
        highContrast: '$base12',

        white: '$whiteA12',
        black: '$blackA12',
      },
      space: {
        1: '4px',
        2: '8px',
        3: '16px',
        4: '24px',
        5: '32px',
        6: '40px',
      },
      fontSizes: {
        1: '14px',
        2: '24px',
        3: '30px',
        4: '56px',
        5: '68px',
      },
      fonts: {
        untitled:
          'Untitled Sans, -apple-system, system-ui, sans-serif',
      },
      fontWeights: {
        1: 400,
        2: 500,
        3: 600,
      },
      lineHeights: {
        1: '22px',
        2: '32px',
        3: '38px',
        4: '64px',
        5: '76px',
      },
      letterSpacings: {},
      sizes: {
        none: 0,
        full: '100%',
        vh: '100vh',
        vw: '100vw',
        1: '4px',
        2: '8px',
        3: '16px',
        4: '32px',
        5: '64px',
        6: '128px',
        s1: '640px',
        s2: '768px',
        s3: '1024px',
        s4: '1280px',
        s5: '1536px',
      },
      borderWidths: {},
      borderStyles: {},
      radii: {
        sharp: '0',
        dull: '4px',
        soft: '12px',
        round: '50%',
        pill: '9999px',
      },
      shadows: {},
      zIndices: {
        1: '100',
        2: '200',
        3: '300',
        4: '400',
        5: '999',
      },
      transitions: {},
    },
    media: {
      bp1: '(min-width: 640px)',
      bp2: '(min-width: 768px)',
      bp3: '(min-width: 1024px)',
      bp4: '(min-width: 1280px)',
      bp5: '(min-width: 1536px)',
    },
    utils: {
      p: (value: Stitches.PropertyValue<'padding'>) => ({
        padding: value,
      }),
      pt: (value: Stitches.PropertyValue<'paddingTop'>) => ({
        paddingTop: value,
      }),
      pr: (value: Stitches.PropertyValue<'paddingRight'>) => ({
        paddingRight: value,
      }),
      pb: (value: Stitches.PropertyValue<'paddingBottom'>) => ({
        paddingBottom: value,
      }),
      pl: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
        paddingLeft: value,
      }),
      px: (value: Stitches.PropertyValue<'paddingLeft'>) => ({
        paddingLeft: value,
        paddingRight: value,
      }),
      py: (value: Stitches.PropertyValue<'paddingTop'>) => ({
        paddingTop: value,
        paddingBottom: value,
      }),
      m: (value: Stitches.PropertyValue<'margin'>) => ({
        margin: value,
      }),
      mt: (value: Stitches.PropertyValue<'marginTop'>) => ({
        marginTop: value,
      }),
      mr: (value: Stitches.PropertyValue<'marginRight'>) => ({
        marginRight: value,
      }),
      mb: (value: Stitches.PropertyValue<'marginBottom'>) => ({
        marginBottom: value,
      }),
      ml: (value: Stitches.PropertyValue<'marginLeft'>) => ({
        marginLeft: value,
      }),
      mx: (value: Stitches.PropertyValue<'marginLeft'>) => ({
        marginLeft: value,
        marginRight: value,
      }),
      my: (value: Stitches.PropertyValue<'marginTop'>) => ({
        marginTop: value,
        marginBottom: value,
      }),
      backgroundClip: (
        value: Stitches.PropertyValue<'backgroundClip'>
      ) => ({
        WebkitBackgroundClip: value,
        backgroundClip: value,
      }),
      linearGradient: (
        value: Stitches.PropertyValue<'backgroundImage'>
      ) => ({
        backgroundImage: `linear-gradient(${value})`,
      }),
    },
  });

export type CSS = Stitches.CSS<typeof config>;

export const altTheme = createTheme('alt-theme', {
  colors: {
    ...tomato,
    ...red,
    ...crimson,
    ...pink,
    ...plum,
    ...purple,
    ...violet,
    ...indigo,
    ...mauve,
    ...whiteA,
    ...blackA,

    base1: '$mauve1',
    base2: '$mauve2',
    base3: '$mauve3',
    base4: '$mauve4',
    base5: '$mauve5',
    base6: '$mauve6',
    base7: '$mauve7',
    base8: '$mauve8',
    base9: '$mauve9',
    base10: '$mauve10',
    base11: '$mauve11',
    base12: '$mauve12',

    accent1: '$crimson1',
    accent2: '$crimson2',
    accent3: '$crimson3',
    accent4: '$crimson4',
    accent5: '$crimson5',
    accent6: '$crimson6',
    accent7: '$crimson7',
    accent8: '$crimson8',
    accent9: '$crimson9',
    accent10: '$crimson10',
    accent11: '$crimson11',
    accent12: '$crimson12',

    secondary1: '$plum1',
    secondary2: '$plum2',
    secondary3: '$plum3',
    secondary4: '$plum4',
    secondary5: '$plum5',
    secondary6: '$plum6',
    secondary7: '$plum7',
    secondary8: '$plum8',
    secondary9: '$plum9',
    secondary10: '$plum10',
    secondary11: '$plum11',
    secondary12: '$plum12',

    primary1: '$violet1',
    primary2: '$violet2',
    primary3: '$violet3',
    primary4: '$violet4',
    primary5: '$violet5',
    primary6: '$violet6',
    primary7: '$violet7',
    primary8: '$violet8',
    primary9: '$violet9',
    primary10: '$violet10',
    primary11: '$violet11',
    primary12: '$violet12',

    shade1: '$indigo1',
    shade2: '$indigo2',
    shade3: '$indigo3',
    shade4: '$indigo4',
    shade5: '$indigo5',
    shade6: '$indigo6',
    shade7: '$indigo7',
    shade8: '$indigo8',
    shade9: '$indigo9',
    shade10: '$indigo10',
    shade11: '$indigo11',
    shade12: '$indigo12',

    tint1: '$purple1',
    tint2: '$purple2',
    tint3: '$purple3',
    tint4: '$purple4',
    tint5: '$purple5',
    tint6: '$purple6',
    tint7: '$purple7',
    tint8: '$purple8',
    tint9: '$purple9',
    tint10: '$purple10',
    tint11: '$purple11',
    tint12: '$purple12',

    appBg1: '$base1',
    appBg2: '$base2',
    appBg3: '$base9',
    appBg4: '$base10',
    lowContrast: '$base11',
    highContrast: '$base12',

    white: '$whiteA12',
    black: '$blackA12',
  },
});

export const darkTheme = createTheme('dark-theme', {
  colors: {
    ...indigoDark,
    ...blueDark,
    ...skyDark,
    ...cyanDark,
    ...slateDark,
    ...whiteA,
    ...blackA,

    base1: '$slate1',
    base2: '$slate2',
    base3: '$slate3',
    base4: '$slate4',
    base5: '$slate5',
    base6: '$slate6',
    base7: '$slate7',
    base8: '$slate8',
    base9: '$slate9',
    base10: '$slate10',
    base11: '$slate11',
    base12: '$slate12',

    accent1: '$sky1',
    accent2: '$sky2',
    accent3: '$sky3',
    accent4: '$sky4',
    accent5: '$sky5',
    accent6: '$sky6',
    accent7: '$sky7',
    accent8: '$sky8',
    accent9: '$sky9',
    accent10: '$sky10',
    accent11: '$sky11',
    accent12: '$sky12',

    secondary1: '$indigo1',
    secondary2: '$indigo2',
    secondary3: '$indigo3',
    secondary4: '$indigo4',
    secondary5: '$indigo5',
    secondary6: '$indigo6',
    secondary7: '$indigo7',
    secondary8: '$indigo8',
    secondary9: '$indigo9',
    secondary10: '$indigo10',
    secondary11: '$indigo11',
    secondary12: '$indigo12',

    primary1: '$blue1',
    primary2: '$blue2',
    primary3: '$blue3',
    primary4: '$blue4',
    primary5: '$blue5',
    primary6: '$blue6',
    primary7: '$blue7',
    primary8: '$blue8',
    primary9: '$blue9',
    primary10: '$blue10',
    primary11: '$blue11',
    primary12: '$blue12',

    shade1: '$indigo1',
    shade2: '$indigo2',
    shade3: '$indigo3',
    shade4: '$indigo4',
    shade5: '$indigo5',
    shade6: '$indigo6',
    shade7: '$indigo7',
    shade8: '$indigo8',
    shade9: '$indigo9',
    shade10: '$indigo10',
    shade11: '$indigo11',
    shade12: '$indigo12',

    tint1: '$sky1',
    tint2: '$sky2',
    tint3: '$sky3',
    tint4: '$sky4',
    tint5: '$sky5',
    tint6: '$sky6',
    tint7: '$sky7',
    tint8: '$sky8',
    tint9: '$sky9',
    tint10: '$sky10',
    tint11: '$sky11',
    tint12: '$sky12',

    appBg1: '$base1',
    appBg2: '$base2',
    appBg3: '$base9',
    appBg4: '$base10',
    lowContrast: '$base11',
    highContrast: '$base12',

    white: '$whiteA12',
    black: '$blackA12',
  },
});
